background #161618
foreground #ffffff
cursor #cccccc
cursor_text_color #999999
selection_foreground #161618
selection_background #ffffff
color0 #161618
color1 #ff5370
color2 #a9dc76
color3 #ffcb6b
color4 #89ddff
color5 #c792ea
color6 #80cbc4
color7 #ffffff
color8 #5c5c62
color9 #ff5370
color10 #a9dc76
color11 #ffcb6b
color12 #89ddff
color13 #c792ea
color14 #80cbc4
color15 #ffffff
