background #241e1a
foreground #ede0d4
cursor #cdc0b4
cursor_text_color #988c80
selection_foreground #241e1a
selection_background #ede0d4
color0 #241e1a
color1 #d46a5a
color2 #a3b88a
color3 #e0b97c
color4 #c2855a
color5 #b89ab3
color6 #7ab8a0
color7 #ede0d4
color8 #665a50
color9 #d46a5a
color10 #a3b88a
color11 #e0b97c
color12 #c2855a
color13 #b89ab3
color14 #7ab8a0
color15 #ede0d4
