background #1e2229
foreground #dce3ed
cursor #bac5d1
cursor_text_color #848f9c
selection_foreground #1e2229
selection_background #dce3ed
color0 #1e2229
color1 #e06c75
color2 #7bc99d
color3 #d4a043
color4 #7ab0d4
color5 #a990d4
color6 #6ec4c8
color7 #dce3ed
color8 #5d6675
color9 #e06c75
color10 #7bc99d
color11 #d4a043
color12 #7ab0d4
color13 #a990d4
color14 #6ec4c8
color15 #dce3ed
