background #221a17
foreground #f0e6dc
cursor #d0c6bc
cursor_text_color #9a9086
selection_foreground #221a17
selection_background #f0e6dc
color0 #221a17
color1 #e06c5a
color2 #c4a86a
color3 #e0b04a
color4 #d48a5a
color5 #c09ab3
color6 #6ab8a0
color7 #f0e6dc
color8 #635548
color9 #e06c5a
color10 #c4a86a
color11 #e0b04a
color12 #d48a5a
color13 #c09ab3
color14 #6ab8a0
color15 #f0e6dc
